services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yolo-fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models        # changed ../ to ./
      - ./mlruns:/app/mlruns        # changed ../ to ./
    depends_on:
      - mlflow
    networks:
      - mlops-network

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow-server
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns            # changed ../ to ./
      - ./mlflow.db:/mlflow.db
    command: >
      mlflow server
      --backend-store-uri /mlruns
      --default-artifact-root /mlruns
      --host 0.0.0.0
      --port 5000
    networks:
      - mlops-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus-server
    ports:
      - "9091:9090"                 # fixed port conflict
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml  # fixed path
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - mlops-network

  grafana:
    image: grafana/grafana
    container_name: grafana-dashboard
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - mlops-network

volumes:
  grafana-storage:

networks:
  mlops-network:
    driver: bridge